
# Getting This Exception at the production .I am Trying to reproduce at local but unable to find out reason for this exception

Exception: com.amazonaws.services.cloudfront.model.InvalidArgumentException: Your request contains a caller reference that was used for a previous invalidation batch for the same distribution.
Invalidating  Amazon CloudFront .Tried reproduce at local system but unable to find reason .Nothing was mentioned over AWS  CloudFront Documentation.

        