
# try except not passing

stack = []

try:
    top = stack.pop()
except IndexError:
    pass


Error: IndexError: pop from empty list
I want the try except statement to pass if the stack can't be popped, but an error is still being thrown.

        