
# AttributeError: 'function' object has no attribute 'clear_cache' [closed]







Closed. This question needs debugging details. It is not currently accepting answers.
                        
                    










 Edit the question to include desired behavior, a specific problem or error, and the shortest code necessary to reproduce the problem. This will help others answer the question.


Closed 53 mins ago.







                        Improve this question
                    



Does anyone know how to solve an error like this?
  File "/home/me/usr/oishi_odoo14/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/me/usr/oishi_odoo14/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'function' object has no attribute 'clear_cache'

kind regards

        