
# how to run the rest of the test code after a failed call to the contract in hardhat?

I'm trying to write a test for my smart contract in hardhat with js, I want to check somethings in case a call to my contract fails the problem is that when the line of "failed contract call" runs it reverts the whole block of test and will not run the rest of it.
how can I make it work?
some code 1
await contract.function()
// contract call fails intentionally
some code 2

I need the result of "some code 2" but I just get an error that the call has failed.

        