
# error E966 `nlp.add_pipe` now takes the string name of the registered component factory

!git clone https://github.com/abdullah-abunada/bert-extractive-summarizer
!pip install -r /content/bert-extractive-summarizer/requirements.txt

When importing the Summarizer function as below:
from summarizer import Summarizer 

I got this error
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-d5dc47fea1c7> in <module>
----> 1 from summarizer import Summarizer

4 frames
/usr/local/lib/python3.7/dist-packages/spacy/language.py in add_pipe(self, factory_name, name, before, after, first, last, source, config, raw_config, validate)
    777             bad_val = repr(factory_name)
    778             err = Errors.E966.format(component=bad_val, name=name)
--> 779             raise ValueError(err)
    780         name = name if name is not None else factory_name
    781         if name in self.component_names:

ValueError: [E966] `nlp.add_pipe` now takes the string name of the registered component factory, not a callable component. Expected string, but got <spacy.pipeline.sentencizer.Sentencizer object at 0x7f176866f550> (name: 'None').
- If you created your component with `nlp.create_pipe('name')`: remove nlp.create_pipe and call `nlp.add_pipe('name')` instead.

- If you passed in a component like `TextCategorizer()`: call `nlp.add_pipe` with the string name instead, e.g. `nlp.add_pipe('textcat')`.

- If you're using a custom component: Add the decorator `@Language.component` (for function components) or `@Language.factory` (for class components / factories) to your custom component and assign it a name, e.g. `@Language.component('your_name')`. You can then run `nlp.add_pipe('your_name')` to add it to the pipeline.

Do you have any idea of how to fix it?

        